// Dumps the live database into backend/db/seed.sql as a real-data backup.
// Run with `npm run snapshot`. Re-running `npm run seed` later restores
// exactly this snapshot (same schema, same rows, same ids).
require('dotenv').config();

const fs = require('fs');
const path = require('path');
const pool = require('../src/config/db');

const SCHEMA = `-- FinancialIQ PostgreSQL schema & seed data
-- Seed data below is a snapshot of real account data, generated by \`npm run snapshot\`.
-- Re-running \`npm run seed\` restores exactly this snapshot.

DROP TABLE IF EXISTS investments;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS recurring_expenses;
DROP TABLE IF EXISTS accounts;

-- Bank accounts, CDs, IRAs, 401k/brokerage accounts, home equity
CREATE TABLE accounts (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  type VARCHAR(20) NOT NULL CHECK (type IN ('checking', 'savings', 'cash', 'cd', 'ira', '401k', 'brokerage', 'home_equity')),
  institution VARCHAR(120),
  balance NUMERIC(14, 2) NOT NULL DEFAULT 0,
  interest_rate NUMERIC(5, 3),
  maturity_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Recurring monthly bills (auto, insurance, utilities, subscriptions, etc.)
CREATE TABLE recurring_expenses (
  id SERIAL PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL DEFAULT 'other',
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  day_of_month INTEGER NOT NULL CHECK (day_of_month BETWEEN 1 AND 31),
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Daily expenses / income tied to an account
CREATE TABLE transactions (
  id SERIAL PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  description VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL DEFAULT 'other',
  amount NUMERIC(12, 2) NOT NULL,
  recurring_expense_id INTEGER REFERENCES recurring_expenses(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Investment holdings tied to an account
CREATE TABLE investments (
  id SERIAL PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  symbol VARCHAR(20) NOT NULL,
  name VARCHAR(120) NOT NULL,
  asset_class VARCHAR(20) NOT NULL CHECK (asset_class IN ('stock', 'bond', 'etf', 'mutual_fund', 'cash')),
  shares NUMERIC(14, 4) NOT NULL DEFAULT 0,
  cost_basis NUMERIC(14, 2) NOT NULL DEFAULT 0,
  current_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_recurring_expenses_account_id ON recurring_expenses(account_id);
CREATE INDEX idx_transactions_account_id ON transactions(account_id);
CREATE INDEX idx_transactions_recurring_expense_id ON transactions(recurring_expense_id);
CREATE INDEX idx_investments_account_id ON investments(account_id);
`;

function str(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function num(value) {
  return value === null || value === undefined ? 'NULL' : String(value);
}

function bool(value) {
  return value ? 'true' : 'false';
}

function date(value) {
  if (value === null || value === undefined) return 'NULL';
  const iso = value instanceof Date ? value.toISOString().slice(0, 10) : String(value).slice(0, 10);
  return `'${iso}'`;
}

function buildInsert(table, columns, rows, rowToValues) {
  if (rows.length === 0) return `-- ${table}: no rows\n`;
  const tuples = rows.map((row) => `  (${rowToValues(row).join(', ')})`).join(',\n');
  const maxId = Math.max(...rows.map((r) => r.id));
  return (
    `INSERT INTO ${table} (${columns.join(', ')}) VALUES\n${tuples};\n` +
    `SELECT setval('${table}_id_seq', ${maxId});\n`
  );
}

async function run() {
  const accounts = (await pool.query('SELECT * FROM accounts ORDER BY id')).rows;
  const recurringExpenses = (await pool.query('SELECT * FROM recurring_expenses ORDER BY id')).rows;
  const transactions = (await pool.query('SELECT * FROM transactions ORDER BY id')).rows;
  const investments = (await pool.query('SELECT * FROM investments ORDER BY id')).rows;

  const parts = [SCHEMA, '\n-- Seed data (snapshot of real accounts)\n\n'];

  parts.push(
    buildInsert('accounts', ['id', 'name', 'type', 'institution', 'balance', 'interest_rate', 'maturity_date'], accounts, (a) => [
      num(a.id),
      str(a.name),
      str(a.type),
      str(a.institution),
      num(a.balance),
      num(a.interest_rate),
      date(a.maturity_date),
    ])
  );
  parts.push('\n');

  parts.push(
    buildInsert(
      'recurring_expenses',
      ['id', 'account_id', 'name', 'category', 'amount', 'day_of_month', 'active'],
      recurringExpenses,
      (r) => [num(r.id), num(r.account_id), str(r.name), str(r.category), num(r.amount), num(r.day_of_month), bool(r.active)]
    )
  );
  parts.push('\n');

  parts.push(
    buildInsert(
      'transactions',
      ['id', 'account_id', 'date', 'description', 'category', 'amount', 'recurring_expense_id'],
      transactions,
      (t) => [num(t.id), num(t.account_id), date(t.date), str(t.description), str(t.category), num(t.amount), num(t.recurring_expense_id)]
    )
  );
  parts.push('\n');

  parts.push(
    buildInsert(
      'investments',
      ['id', 'account_id', 'symbol', 'name', 'asset_class', 'shares', 'cost_basis', 'current_price'],
      investments,
      (i) => [num(i.id), num(i.account_id), str(i.symbol), str(i.name), str(i.asset_class), num(i.shares), num(i.cost_basis), num(i.current_price)]
    )
  );

  const outPath = path.join(__dirname, '../db/seed.sql');
  fs.writeFileSync(outPath, parts.join(''));
  console.log(
    `Wrote db/seed.sql: ${accounts.length} accounts, ${recurringExpenses.length} recurring expenses, ${transactions.length} transactions, ${investments.length} investments.`
  );
  await pool.end();
}

run().catch((err) => {
  console.error('Failed to snapshot database:', err.message);
  process.exit(1);
});
