-- FinancialIQ PostgreSQL schema & seed data
-- Seed data below is a snapshot of real account data, generated by `npm run snapshot`.
-- Re-running `npm run seed` restores exactly this snapshot.

DROP TABLE IF EXISTS investments;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS recurring_expenses;
DROP TABLE IF EXISTS accounts;

-- Bank accounts, CDs, IRAs, 401k/brokerage accounts, home equity
CREATE TABLE accounts (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  type VARCHAR(20) NOT NULL CHECK (type IN ('checking', 'savings', 'cash', 'cd', 'ira', '401k', 'brokerage', 'home_equity')),
  institution VARCHAR(120),
  balance NUMERIC(14, 2) NOT NULL DEFAULT 0,
  interest_rate NUMERIC(5, 3),
  maturity_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Recurring monthly bills (auto, insurance, utilities, subscriptions, etc.)
CREATE TABLE recurring_expenses (
  id SERIAL PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL DEFAULT 'other',
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  day_of_month INTEGER NOT NULL CHECK (day_of_month BETWEEN 1 AND 31),
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Daily expenses / income tied to an account
CREATE TABLE transactions (
  id SERIAL PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  description VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL DEFAULT 'other',
  amount NUMERIC(12, 2) NOT NULL,
  recurring_expense_id INTEGER REFERENCES recurring_expenses(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Investment holdings tied to an account
CREATE TABLE investments (
  id SERIAL PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  symbol VARCHAR(20) NOT NULL,
  name VARCHAR(120) NOT NULL,
  asset_class VARCHAR(20) NOT NULL CHECK (asset_class IN ('stock', 'bond', 'etf', 'mutual_fund', 'cash')),
  shares NUMERIC(14, 4) NOT NULL DEFAULT 0,
  cost_basis NUMERIC(14, 2) NOT NULL DEFAULT 0,
  current_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_recurring_expenses_account_id ON recurring_expenses(account_id);
CREATE INDEX idx_transactions_account_id ON transactions(account_id);
CREATE INDEX idx_transactions_recurring_expense_id ON transactions(recurring_expense_id);
CREATE INDEX idx_investments_account_id ON investments(account_id);

-- Seed data (snapshot of real accounts)

INSERT INTO accounts (id, name, type, institution, balance, interest_rate, maturity_date) VALUES
  (1, 'Wells Fargo Primary', 'checking', 'Wells Fargo', 136786.00, NULL, NULL),
  (2, 'Bank of America Primary', 'checking', 'Bank of America', 21666.00, NULL, NULL),
  (3, 'Capital One Travel Account', 'checking', 'Capital One', 5094.00, NULL, NULL),
  (4, 'BOA 3.25 7 Month ', 'cd', 'Bank Of America', 10395.00, 3.250, '2026-12-12'),
  (5, 'Capital One 14 Month', 'cd', 'Capital One', 10500.00, 3.900, '2027-06-03'),
  (6, 'Capital One 14 Month - 3.75', 'cd', 'Capital One', 20000.00, 3.750, '2027-04-11'),
  (7, 'WF - CD (7 Month)', 'cd', 'Wells Fargo', 10403.00, 3.500, '2026-12-30'),
  (8, 'WF 15 Mo CD 3.44', 'cd', 'Wells Fargo', 10000.00, 4.000, '2027-10-31'),
  (9, 'Capital One 360 Performance', 'savings', 'Capital One', 51280.00, 3.000, NULL),
  (10, 'Apple Savings', 'savings', 'Apple', 11770.00, 3.400, NULL),
  (11, 'Wells Fargo Savings (Brokerage Account)', 'savings', 'Wells Fargo', 4443.00, 0.010, NULL),
  (12, 'American Express Savings', 'savings', 'American Express', 11267.00, 3.000, NULL),
  (13, 'Safe Deposit Box', 'cash', 'Home Office', 27050.00, NULL, NULL),
  (14, 'Pocket Cash', 'cash', 'Home Office', 2500.00, NULL, NULL),
  (15, 'Next Paycheck', 'cash', 'Employment Pay', 3930.00, NULL, NULL),
  (16, 'Discretionary - Cash App', 'cash', 'Cash App - Pocket', 490.00, NULL, NULL),
  (18, 'Charles Swab - Brokerage', 'brokerage', 'Charles Swab ', 1134.00, NULL, NULL),
  (19, 'Robinhood Brokerage', 'brokerage', 'Robinhood', 100.00, NULL, NULL),
  (20, 'Gaming Cash Plus HISD Vacation', 'cash', 'HISD + Gaming', 5240.00, NULL, NULL),
  (21, 'Travel Account - Residual', 'cash', 'Travel Account', 300.00, NULL, NULL),
  (22, 'Fidelity IRA', 'ira', 'Fidelity Investments', 138209.00, NULL, NULL),
  (23, 'Pension', '401k', 'Teacher Retirement System', 57565.00, NULL, NULL),
  (25, 'Home Equity', 'home_equity', '17615 Magnolia Cr', 375000.00, NULL, NULL);
SELECT setval('accounts_id_seq', 25);

-- transactions: no rows

INSERT INTO investments (id, account_id, symbol, name, asset_class, shares, cost_basis, current_price) VALUES
  (1, 18, 'NVDA', 'NVIDIA Corporation (NVDA)', 'stock', 10.0000, 1680.00, 215.26);
SELECT setval('investments_id_seq', 1);
